window.PLAYBOOK_DATA = {
  "source": "https://docs.google.com/spreadsheets/d/1b96m9VfSZ76zbSnjtjvfErzRu7M8itnBYojPgq7HoqM/edit",
  "tab": "Plays 2026",
  "ratingVersion": 1,
  "ratingColumn": "R/P/RPO",
  "playCount": 88,
  "plays": [
    {
      "id": "sheet-1",
      "set": "A",
      "slot": "1",
      "formation": "Shotgun Empty Bunch Open",
      "play": "Crossers",
      "preSnap": "",
      "mainRead": "",
      "playType": "Quick Pass",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-2",
      "set": "A",
      "slot": "2",
      "formation": "Shotgun Bunch Wide",
      "play": "Quick Rub Return",
      "preSnap": "",
      "mainRead": "",
      "playType": "Quick Pass",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-3",
      "set": "A",
      "slot": "3",
      "formation": "Shotgun Y Off Trip Wk",
      "play": "Quick Fork Zig",
      "preSnap": "",
      "mainRead": "",
      "playType": "Delayed Inside Pass or Out",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-4",
      "set": "B",
      "slot": "1",
      "formation": "Shotgun Wing Slot Over",
      "play": "Power Read",
      "preSnap": "",
      "mainRead": "",
      "playType": "QB Option",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-5",
      "set": "B",
      "slot": "2",
      "formation": "Shotgun Bunch TE",
      "play": "Whips",
      "preSnap": "",
      "mainRead": "",
      "playType": "Whips",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-6",
      "set": "B",
      "slot": "3",
      "formation": "Shotgun Trips",
      "play": "Strong Flood",
      "preSnap": "Zig X",
      "mainRead": "",
      "playType": "Outside Layers",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-7",
      "set": "C",
      "slot": "1",
      "formation": "Shotgun 5WR",
      "play": "Double Pivot",
      "preSnap": "",
      "mainRead": "",
      "playType": "Deep Comeback w/ More",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-8",
      "set": "C",
      "slot": "2",
      "formation": "Shotgun 5WR",
      "play": "Shallow Cross",
      "preSnap": "",
      "mainRead": "",
      "playType": "Deep Comeback w/ More",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-9",
      "set": "C",
      "slot": "3",
      "formation": "Shotgun Gate",
      "play": "Sprint Smash",
      "preSnap": "",
      "mainRead": "",
      "playType": "Deep Comeback w/ More",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-10",
      "set": "D",
      "slot": "1",
      "formation": "Shotgun Doubles",
      "play": "PA Comebacks",
      "preSnap": "",
      "mainRead": "",
      "playType": "Deep comeback",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-11",
      "set": "D",
      "slot": "2",
      "formation": "Shotgun Bunch Str Offset",
      "play": "MTN PA X Over",
      "preSnap": "Square Comeback, R1 Streak",
      "mainRead": "",
      "playType": "Deep comeback",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-12",
      "set": "D",
      "slot": "3",
      "formation": "Shotgun Trips TE",
      "play": "Verticals",
      "preSnap": "Texas R1, Square Comeback",
      "mainRead": "",
      "playType": "Deep comeback",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-13",
      "set": "E",
      "slot": "1",
      "formation": "Shotgun Cluster HB Str",
      "play": "Verticals",
      "preSnap": "Drag X, Streak Triangle",
      "mainRead": "",
      "playType": "Streak and Under",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-14",
      "set": "E",
      "slot": "2",
      "formation": "Shotgun Trips Offset",
      "play": "Smash",
      "preSnap": "",
      "mainRead": "",
      "playType": "Streak and Under",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-15",
      "set": "E",
      "slot": "3",
      "formation": "Shotgun Doubles",
      "play": "Y Shallow Cross",
      "preSnap": "",
      "mainRead": "",
      "playType": "Middle Layers",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-16",
      "set": "F",
      "slot": "1",
      "formation": "Shotgun Spread",
      "play": "Four Verticals",
      "preSnap": "Drag slots, streak R1",
      "mainRead": "R1 deep middle when the safefies split",
      "playType": "Deep RB Pass",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-17",
      "set": "F",
      "slot": "2",
      "formation": "Shotgun Wide",
      "play": "PA Double Switch",
      "preSnap": "R1 Block",
      "mainRead": "",
      "playType": "Very Deep Pass",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-18",
      "set": "F",
      "slot": "3",
      "formation": "Shotgun 5WR",
      "play": "Shock",
      "preSnap": "Streak X, Coemback Square",
      "mainRead": "",
      "playType": "Deep or Slant",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-19",
      "set": "G",
      "slot": "1",
      "formation": "Shotgun Trey Open",
      "play": "Shallow Cross Screen",
      "preSnap": "",
      "mainRead": "",
      "playType": "Flat Screen or HB Swing",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-20",
      "set": "G",
      "slot": "2",
      "formation": "Shotgun Doubles",
      "play": "Orbit RPO Read Y Flat",
      "preSnap": "",
      "mainRead": "",
      "playType": "Swing & Flat",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-21",
      "set": "G",
      "slot": "3",
      "formation": "Shotgun Y Trips X Off",
      "play": "Orbit HB Cross Screen",
      "preSnap": "",
      "mainRead": "",
      "playType": "Swing & Screen",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-22",
      "set": "H",
      "slot": "1",
      "formation": "Widcat Bunch HB Str",
      "play": "Speed Option",
      "preSnap": "",
      "mainRead": "",
      "playType": "Speed Option",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-23",
      "set": "H",
      "slot": "2",
      "formation": "Shotgun Doubles",
      "play": "Speed Option",
      "preSnap": "",
      "mainRead": "",
      "playType": "Speed Option",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-24",
      "set": "H",
      "slot": "3",
      "formation": "Widcat Bunch HB Str",
      "play": "Sweep",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside run",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-25",
      "set": "I",
      "slot": "1",
      "formation": "Shotgun Trips",
      "play": "QB Slot Option",
      "preSnap": "",
      "mainRead": "",
      "playType": "Triple Option",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-26",
      "set": "I",
      "slot": "2",
      "formation": "Shotgun Ace Offset",
      "play": "Orbit WR Option",
      "preSnap": "",
      "mainRead": "",
      "playType": "Triple Option",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-27",
      "set": "I",
      "slot": "3",
      "formation": "Shotgun Trips HB Wk",
      "play": "HB Direct",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside run",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-28",
      "set": "J",
      "slot": "1",
      "formation": "Shotgun Y Off Trips Nasty",
      "play": "RPO Read Y Flat",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Flat",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-29",
      "set": "J",
      "slot": "2",
      "formation": "Shotgun Y Trips X Off",
      "play": "MTN RPO Read X Slide",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Flat",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-30",
      "set": "J",
      "slot": "3",
      "formation": "Shotgun Y Off Trips",
      "play": "HB Direct Snap",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside Run",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-31",
      "set": "K",
      "slot": "1",
      "formation": "Singleback Bunch TE",
      "play": "Stretch Alert Bubble",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Bubble",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-32",
      "set": "K",
      "slot": "2",
      "formation": "Shotgun Trips",
      "play": "RPO Alert Bubble",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Bubble",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-33",
      "set": "K",
      "slot": "3",
      "formation": "Pustol Wing Slot Over",
      "play": "Zone Alert Bubble",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Bubble",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-34",
      "set": "L",
      "slot": "1",
      "formation": "Shotgun Bunch Offset",
      "play": "Orbit RPO Alert Slant",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Slant or Screen",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-35",
      "set": "L",
      "slot": "2",
      "formation": "Shotbun Bunch Open Offset",
      "play": "RPO Peek WR Screen",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Out",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-36",
      "set": "L",
      "slot": "3",
      "formation": "Shotgun Wing Trips",
      "play": "MTN PA FK Screen Wheel",
      "preSnap": "",
      "mainRead": "",
      "playType": "Bubble or Wheel",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-37",
      "set": "M",
      "slot": "1",
      "formation": "Pistol Trips",
      "play": "PA X Dagger",
      "preSnap": "Drag X",
      "mainRead": "",
      "playType": "Deep cross or Drag",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-38",
      "set": "M",
      "slot": "2",
      "formation": "Shotgun Bunch Open Offset",
      "play": "PA Boot Over",
      "preSnap": "Circle Comeback",
      "mainRead": "",
      "playType": "Deep comeback",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-39",
      "set": "M",
      "slot": "3",
      "formation": "Pistol U Off",
      "play": "PA Boot Y Drag",
      "preSnap": "",
      "mainRead": "",
      "playType": "Deep comeback",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-40",
      "set": "N",
      "slot": "1",
      "formation": "Shotgun Tight Slots HB Wk",
      "play": "Flood",
      "preSnap": "Stem Corner in non-NDL",
      "mainRead": "",
      "playType": "Layers and Corner",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-41",
      "set": "N",
      "slot": "2",
      "formation": "Shotgun Trips TE",
      "play": "Curl Flat",
      "preSnap": "Stem Corner in non-NDL",
      "mainRead": "",
      "playType": "Layers and Corner",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-42",
      "set": "N",
      "slot": "3",
      "formation": "Shotgun Bunch",
      "play": "Bunch Trail",
      "preSnap": "Streak X, Curl Circle, Stel R1 in non-NDL",
      "mainRead": "",
      "playType": "Curl and Corner",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-43",
      "set": "O",
      "slot": "1",
      "formation": "Shotgun Y Off Trips",
      "play": "RPO Read Y Flat",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Flat",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-44",
      "set": "O",
      "slot": "2",
      "formation": "Shotgun Deuce",
      "play": "RPO Read Flat Wheel",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Flat",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-45",
      "set": "O",
      "slot": "3",
      "formation": "Shotgun Y Off Trips Wk",
      "play": "RPO Read Y Flat",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Flat",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-46",
      "set": "P",
      "slot": "1",
      "formation": "Shotgun Bunch Open Offset",
      "play": "Inside Zone",
      "preSnap": "",
      "mainRead": "",
      "playType": "Inside Run",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-47",
      "set": "P",
      "slot": "2",
      "formation": "Wing Slot Over",
      "play": "HB Power G",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside run",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-48",
      "set": "P",
      "slot": "3",
      "formation": "Shotgun Y Off Trips",
      "play": "HB Zone Toss",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside run",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-49",
      "set": "Q",
      "slot": "1",
      "formation": "Shotgun Bunch Offset",
      "play": "Verts HB Under",
      "preSnap": "X Corner, Circle Fade",
      "mainRead": "",
      "playType": "TE Corner",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-50",
      "set": "Q",
      "slot": "2",
      "formation": "Shotgun Spread",
      "play": "Fake Jet FLood",
      "preSnap": "",
      "mainRead": "X Corner or  Y Dropoff",
      "playType": "Slot Corner",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-51",
      "set": "Q",
      "slot": "3",
      "formation": "PA Fork",
      "play": "PA Fork",
      "preSnap": "Comeback Square, Stem X in non-NDL",
      "mainRead": "",
      "playType": "Corner and Comeback",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-52",
      "set": "R",
      "slot": "1",
      "formation": "Shotgun Trey Open HB Str",
      "play": "HB Middle Screen",
      "preSnap": "",
      "mainRead": "",
      "playType": "HB Screen",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-53",
      "set": "R",
      "slot": "2",
      "formation": "Shotgun Bunch TE",
      "play": "MTN Jailbreak Screen",
      "preSnap": "",
      "mainRead": "",
      "playType": "Swing or Screen",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-54",
      "set": "R",
      "slot": "3",
      "formation": "Shotgun Trips HB Wk",
      "play": "HB Angle Screen",
      "preSnap": "",
      "mainRead": "",
      "playType": "HB Screen",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-55",
      "set": "S",
      "slot": "1",
      "formation": "Shotgun Wing Trips",
      "play": "DBL MTN RPO Peek Pop",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Pop",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-56",
      "set": "S",
      "slot": "2",
      "formation": "Shotgun Doubles",
      "play": "Orbit HB Slip Screen",
      "preSnap": "",
      "mainRead": "",
      "playType": "Swing & Screen",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-57",
      "set": "S",
      "slot": "3",
      "formation": "Shotgun Trips HB Wk",
      "play": "MTN WR Mid Screen",
      "preSnap": "",
      "mainRead": "",
      "playType": "WR Screen, Swing Slant",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-58",
      "set": "T",
      "slot": "1",
      "formation": "Singleback Wing Slot Over",
      "play": "HB Slant 18",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside run",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-59",
      "set": "T",
      "slot": "2",
      "formation": "Pistol U Off",
      "play": "HB Stretch",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside run",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-60",
      "set": "T",
      "slot": "3",
      "formation": "Singleback Wing Slot Over",
      "play": "26 Duo",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside run",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-61",
      "set": "U",
      "slot": "1",
      "formation": "Shotgun F Twins Over",
      "play": "Jet QB Power",
      "preSnap": "",
      "mainRead": "",
      "playType": "QB Power",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-62",
      "set": "U",
      "slot": "2",
      "formation": "Shotgun Y Trips X Off",
      "play": "Orbit RPO QB Power",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO QB Power",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-63",
      "set": "U",
      "slot": "3",
      "formation": "Shotgun Ace Slot",
      "play": "QB Power",
      "preSnap": "",
      "mainRead": "",
      "playType": "QB Power",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-64",
      "set": "V",
      "slot": "1",
      "formation": "Shotgun Empty Bunch Wide",
      "play": "Z Spot N Go",
      "preSnap": "",
      "mainRead": "",
      "playType": "Tricky Delayed Deep Middle",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-65",
      "set": "V",
      "slot": "2",
      "formation": "Shotgun Empty Base Flex",
      "play": "Middle Hi Lo",
      "preSnap": "Motion Square in, Streak Square",
      "mainRead": "",
      "playType": "Tricky Deep Fade",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-66",
      "set": "V",
      "slot": "3",
      "formation": "I Form Tight",
      "play": "Flea Flicker",
      "preSnap": "Streak X and R1",
      "mainRead": "",
      "playType": "Tricky Middle Streak",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-67",
      "set": "W",
      "slot": "1",
      "formation": "Shotgun Trips HB Wk",
      "play": "MTN Wheel Levels Switch",
      "preSnap": "",
      "mainRead": "",
      "playType": "Double Drags",
      "zRating": 5,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-68",
      "set": "W",
      "slot": "2",
      "formation": "Shotgun Trio Y-Flex",
      "play": "HB MTN Slot Shake",
      "preSnap": "",
      "mainRead": "",
      "playType": "Double Drags",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-69",
      "set": "W",
      "slot": "3",
      "formation": "Shotgun Bunch STR Offset",
      "play": "HB MTN Trail DBL Post",
      "preSnap": "",
      "mainRead": "",
      "playType": "Drags?",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-70",
      "set": "X",
      "slot": "1",
      "formation": "Shotgun Bunch",
      "play": "Clearout SE Out",
      "preSnap": "RB Corner and Stem in non-NDL, Square Comeback",
      "mainRead": "",
      "playType": "Corner and Comeback",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-71",
      "set": "X",
      "slot": "2",
      "formation": "Shotgun Bunch STR Offset",
      "play": "Corner Strike",
      "preSnap": "Stem Circle and Stem in non-NDL, Square comeback",
      "mainRead": "",
      "playType": "Corner and Comeback",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-72",
      "set": "X",
      "slot": "3",
      "formation": "Shotgun Normal Y Off Close",
      "play": "Y Sail",
      "preSnap": "Square Comeback and stem X",
      "mainRead": "",
      "playType": "Corner and Comeback",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-73",
      "set": "Y",
      "slot": "1",
      "formation": "I Form Hulk",
      "play": "HB Sweep",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside Run",
      "zRating": 4,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-74",
      "set": "Y",
      "slot": "2",
      "formation": "Shotgun Wing Slot Offset",
      "play": "DBL MTN HB Toss",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside run",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-75",
      "set": "Y",
      "slot": "3",
      "formation": "Shotgun Bunch TE",
      "play": "HB Off Tackle",
      "preSnap": "",
      "mainRead": "",
      "playType": "Outside run",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-76",
      "set": "Z",
      "slot": "1",
      "formation": "Shotgun Normal Y Off Close",
      "play": "Jet Touch Pass",
      "preSnap": "",
      "mainRead": "",
      "playType": "Jet Sweep",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-77",
      "set": "Z",
      "slot": "2",
      "formation": "Shotgun Gate",
      "play": "Jet Touch Pass",
      "preSnap": "",
      "mainRead": "",
      "playType": "Jet Sweep",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-78",
      "set": "Z",
      "slot": "3",
      "formation": "Shotgun F Twins Over",
      "play": "Jet Touch Pass",
      "preSnap": "",
      "mainRead": "",
      "playType": "Jet Sweep",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-79",
      "set": "ZZ",
      "slot": "1",
      "formation": "Shotgun Trey Open",
      "play": "H MTN Mesh Post",
      "preSnap": "",
      "mainRead": "",
      "playType": "Drags and Flat Layers",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-80",
      "set": "ZZ",
      "slot": "2",
      "formation": "Shotgun Bunch",
      "play": "Zipper Mesh Post",
      "preSnap": "",
      "mainRead": "",
      "playType": "Drags and Flat",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-81",
      "set": "ZZ",
      "slot": "3",
      "formation": "Shotgun Wing Trio",
      "play": "RPO Peek Y Pop",
      "preSnap": "",
      "mainRead": "",
      "playType": "RPO Pop",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-82",
      "set": "ZZZ",
      "slot": "1",
      "formation": "Shotgun Normal Y Off Close",
      "play": "PA Snag",
      "preSnap": "TE Streak, Slot Drag",
      "mainRead": "TE Streak Slot Crossers",
      "playType": "Pop or Middle Layers",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-83",
      "set": "ZZZ",
      "slot": "2",
      "formation": "Shotgun Cluster HB Str",
      "play": "Post Dig",
      "preSnap": "",
      "mainRead": "",
      "playType": "Zig or Fade",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-84",
      "set": "ZZZ",
      "slot": "3",
      "formation": "Shotgun T Off Trips Nasty",
      "play": "Dagger Whip",
      "preSnap": "",
      "mainRead": "",
      "playType": "Zig or Streak",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-85",
      "set": "ZZZZ",
      "slot": "1",
      "formation": "Shotgun Y Off Trips Wk",
      "play": "Quick Short Post",
      "preSnap": "R1 Zig, Square Slant",
      "mainRead": "",
      "playType": "Zig or Slant",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-86",
      "set": "",
      "slot": "",
      "formation": "Shotgun Bunch STR Wide",
      "play": "Shuffle Dagger",
      "preSnap": "Streak TE and Block RB",
      "mainRead": "Circle",
      "playType": "Deep Post",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-87",
      "set": "",
      "slot": "",
      "formation": "Shotgun Wing Trips",
      "play": "Power Read",
      "preSnap": "",
      "mainRead": "",
      "playType": "QB Option",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    },
    {
      "id": "sheet-88",
      "set": "",
      "slot": "",
      "formation": "Shotgun Wing Trips",
      "play": "HB Swing",
      "preSnap": "",
      "mainRead": "",
      "playType": "RB Swing",
      "zRating": 3,
      "image": "",
      "source": "Plays 2026"
    }
  ]
};
